<h2>Catch custom exception</h2>
<div class="step-text">
<p></p>
<p>A custom exception named <code class="java">InvalidInput</code> has already been defined for you.</p>
<p>Also, a function named <code class="java">aToZ()</code> is already created for you. This function reads  an integer number between 1 and 26 from the console. Then it prints the corresponding number of consecutive alphabetic characters starting from 'a'. In case the console input isn't within the specified range, it throws the <code class="java">InvalidInput</code> exception.</p>
<p>You should use the <code class="java">try/catch</code> statement for the <code class="java">aToZ()</code> function. If it throws the exception, it should be caught and the exception message should be printed.</p>
<p>Note that you don't need to create a <code class="java">main()</code> block, the <code class="java">InvalidInput</code> exception, or the <code class="java">aToZ()</code> function. Just create the try - catch blocks that use the exception and the function.</p><br><b>Sample Input:</b><br><pre><code class="language-no-highlight">1</code></pre><br><b>Sample Output:</b><br><pre><code class="language-no-highlight">a</code></pre><br><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 8 seconds</font><br><br>
</div>
<b>Caution</b><br><br>
You may see errors in your code or execution results due to missing context. Donâ€™t worry about it, just write the solution and press Check.
<br><br>
